### ISSUE TITLE
Improve filename in the DOI lookup?

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-download-service#5]
Currently, the service guesses a name, sometimes producing fun names like `pdf`. Since these names are eventually presented to the user in the Ember app, we might be able to get better names.

One idea is to follow the file URLs found in the lookup using perhaps a HEAD request to see if the server sets a `Content-Disposition` header that may include a filename.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
